version: '3.7'
services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: jobs_container
    volumes:
      - /app/node_modules
      - ./:/app
    stdin_open: true
    tty: true

