version: '3.7'
services:
  react-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: react-app
    volumes:
      - /app/node_modules
      - ./:/app
    stdin_open: true
    tty: true

